<?xml version="1.0" encoding="utf-8"?><Database Name="Northwind" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Northwind;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NorthwindConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CITY" Member="CITies">
    <Type Name="CITY">
      <Column Name="CITY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CITY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="COUNTRY_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="COUNTRY_CITY" Member="COUNTRY" ThisKey="COUNTRY_ID" OtherKey="COUNTRY_ID" Type="COUNTRY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COUNTRY" Member="COUNTRies">
    <Type Name="COUNTRY">
      <Column Name="COUNTRY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="COUNTRY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="COUNTRY_CITY" Member="CITies" ThisKey="COUNTRY_ID" OtherKey="COUNTRY_ID" Type="CITY" />
    </Type>
  </Table>
</Database>